# This is a setup workflow to help test ./install.sh on linux

name: CI-install

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  env:
    GO111MODULE: on
    LISTENSERVER: 127.0.0.1
    LISTENPORT: 4444
    # GITHUBTOKEN:
    # DISCORDWEBHOOKURL:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [macos-latest, ubuntu-latest]
    # env:
      # ATTACKER: ${{ env.LISTENSERVER }}:${{ env.LISTENPORT }}
      # ATTACKERURL: http://${{ env.LISTENSERVER }}:${{ env.LISTENPORT }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -U pip
      env:
        HOMEDIR: ${{ GITHUB_WORKSPACE }}
        STORAGEDIR: ${{ GITHUB_WORKSPACE }}/lazytargets

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: env

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo $HOMEDIR
          echo $STORAGEDIR
          echo $LISTENSERVER
          echo $LISTENPORT
          # sudo -E ./install.sh

