# This is a demo setup workflow to test ./lazyrecon.sh on Mac and linux
# `sudo -E` needs to avoid Permission denied issue

name: test-chromium-action

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
# schedule:
# - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The type of runner that the job will run on
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      # Runs a set of commands using the runners shell
      - name: Install & Recon
        env:
          GO111MODULE: on
          DISCORDWEBHOOKURL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          export HOMEDIR=$HOME
          export HOMEUSER=$RUNNER_USER
          export STORAGEDIR="${HOMEDIR}"/lazytargets
          pwd
          ls -alt
          env
          echo "HOMEUSER=$HOMEUSER"
          echo "HOMEDIR=$HOMEDIR"
          echo "STORAGEDIR=$STORAGEDIR"
          echo "GO111MODULE=$GO111MODULE"
          sudo -E ./install.sh
          ./test/test_install.sh "./test/dependencies_list.txt"
          chromium --headless --disable-gpu --no-sandbox --window-size=1280,720 --screenshot="screenshots/104_16_51_111_8443.png" https://104.16.51.111:8443
          ls -alth
          ls -alth ./screenshots
          file="screenshots/104_16_51_111_8443.png"
          curl -v -H "Content-Type: multipart/form-data" -X POST -F file=@$file $DISCORDWEBHOOKURL
        shell: bash
