# This is a demo setup workflow to test ./lazyrecon.sh on Mac and linux

name: test-recon-action

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
# schedule:
# - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      # Runs a set of commands using the runners shell
      - name: Install
        env:
          DISCORDWEBHOOKURL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUBTOKEN: ${{ secrets.GH_TOKEN }}
          HOMEDIR: ${{ github.workspace }}
          STORAGEDIR: ${{ github.workspace }}
        run: |
          pwd
          ls -alt
          env
          echo "HOMEDIR=$HOMEDIR"
          echo "STORAGEDIR=$STORAGEDIR"
          sudo ./install.sh
          ./test/test_install.sh "./test/dependencies_list.txt"
      - name: Recon
        run: |
          pwd
          ls -alt
          env
          echo "HOMEDIR=$HOMEDIR"
          echo "STORAGEDIR=$STORAGEDIR"
          sudo ./lazyrecon.sh "goldman.com" --wildcard --server --discord
